// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using invoicePage.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace invoicePage.Data
{
    public partial interface ISalesDbContextProcedures
    {
        Task<int> items_CountAsync(int? invoice_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> total_priceAsync(int? invoice_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
