// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace invoicePage.Models
{
    [Table("Invoice")]
    public partial class Invoice
    {
        public Invoice()
        {
            Invoice_Details = new HashSet<Invoice_Detail>();
        }

        [Key]
        public int inv_ID { get; set; }
        public int? items_count { get; set; }
        public double? total_price { get; set; }
        public DateTime? inv_date { get; set; }
        public string? cust_name { get; set; }

        [InverseProperty("inv")]
        public virtual ICollection<Invoice_Detail> Invoice_Details { get; set; }
    }
}