// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace invoicePage.Models
{
    public partial class Invoice_Detail
    {
        [Key]
        public int inv_ID { get; set; }
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string item { get; set; }
        public double? price { get; set; }
        public int? quantity { get; set; }
        public double? total_per_Quantity { get; set; }

        [ForeignKey("inv_ID")]
        [InverseProperty("Invoice_Details")]
        public virtual Invoice inv { get; set; }
    }
}